### ISSUE TITLE
Missing classifier for value too

### ISSUE THREAD

**Issue by sgandon** [veithen/alta#7]
Thank you Andreas for fixing #3 but I just realised that I was using the classifier for values as well.
Because in my artifact I want to store the **.link** files and don't want them to represent local file with the **file:** protocol because they are published for other to use, I cannot use the %url% attribute.
Actually I use the mvn protocol provided by pax-url ( https://ops4j1.jira.com/wiki/display/paxurl/Mvn+Protocol ) like this.

```
<configuration>
        <name>%groupId%-%artifactId%%dashClassifier%.link</name>
        <value>mvn:%groupId%/%artifactId%/%version%//%classifier%</value>
```

notice that I need the real classifier and not the with a starting dash in the value element.
At first in my fork implementation I did only implement the classifier, so I used it like this
`<name>%groupId%-%artifactId%-%classifier%.link</name>
`
But I end-up with many file ending with a -, actually this not a real issue since I know which one I am going to use where as the value is the one I don't know and the one discovered at runtime.
I would suggest you add both _dashClassifier_ and _classifier_.

**Comment by sgandon** [comment]
I'll prepare a PR for this.

**Comment by veithen** [comment]
With the latest change you would configure the plugin as follows:

        <name>%groupId%-%artifactId%%classifier?-@:%.link</name>
        <value>mvn:%groupId%/%artifactId%/%version%//%classifier?@:%</value>

Or, if you want to avoid the trailing slashes for artifacts without classifier:

        <name>%groupId%-%artifactId%%classifier?-@:%.link</name>
        <value>mvn:%groupId%/%artifactId%/%version%%classifier?//@:%</value>
