### ISSUE TITLE
Pitfall to document

### ISSUE THREAD

**Issue by benson-basis** [veithen/alta#9]
I just made an interesting discovery.

If you have the Felix config admin jar in your classpath along with the 5.4.0 framework, SCR won't notice config admin events.

To be more careful and precise:

If you have a pax-exam test, and you provision CA and SCR into the container, but also have CA in the 'outer' classpath, the above bad thing happened.

How does one come to do this? By using the alta-maven-plugin to arrange provisioning from dependencies.

How does one avoid this (other than finding a solution other than alta)? The configuration below.

This might be a reason to give alta the ability to create links for things specified as GAV that are not in the dependency graph at all. 

```
<classpathDependencyExcludes>
    <classpathDependencyExclude>org.apache.felix:org.apache.felix.configadmin</classpathDependencyExclude>
    <classpathDependencyExclude>org.apache.felix:org.apache.felix.scr</classpathDependencyExclude>
</classpathDependencyExcludes>
```

**Comment by benson-basis** [comment]
I'm not so sure I've understood this after all.

**Comment by veithen** [comment]
> This might be a reason to give alta the ability to create links for things specified as GAV that are not in the dependency graph at all.

That's already the case. You can specify individual artifacts in the plugin configuration.
